# role: ethpandaops.general.blockscout

blockscout_container_env:
  # For all env variables, check https://docs.blockscout.com/for-developers/information-and-settings/env-variables
  ETHEREUM_JSONRPC_VARIANT: geth
  ETHEREUM_JSONRPC_HTTP_URL: http://execution:8545/
  ETHEREUM_JSONRPC_TRACE_URL: http://execution:8545/
  MIX_ENV: prod
  PORT: '4000'
  DATABASE_URL: postgresql://postgres:postgres@blockscout-database:5432/blockscout?ssl=false
  SECRET_KEY_BASE: RMgI4C1HSkxsEjdhtGMfwAHfyT6CKWXOgzCboJflfSm4jeAlic52io05KB6mqzc5
  ECTO_USE_SSL: "false"
  NETWORK: "Ethereum"
  SUBNETWORK: "{{ ethereum_network_name }}"
  LINK_TO_OTHER_EXPLORERS: "false"
  OTHER_EXPLORERS: "{}"
  SUPPORTED_CHAINS: "{}"
  # Branding related
  LOGO: /images/blockscout_logo.svg
  FOOTER_LOGO: /images/blockscout_logo.svg
  # Rate limiting
  API_RATE_LIMIT_TIME_INTERVAL: 1s
  API_RATE_LIMIT_BY_IP_TIME_INTERVAL: 5m
  API_RATE_LIMIT: "50"
  API_RATE_LIMIT_BY_KEY: "50"
  API_RATE_LIMIT_BY_WHITELISTED_IP: "50"
  API_RATE_LIMIT_WHITELISTED_IPS: ""
  API_RATE_LIMIT_STATIC_API_KEY: ""
  API_RATE_LIMIT_UI_V2_WITH_TOKEN: "5"
  API_RATE_LIMIT_BY_IP: "3000"
  API_RATE_LIMIT_HAMMER_REDIS_URL: redis://blockscout-cache:6379/1
  API_RATE_LIMIT_UI_V2_TOKEN_TTL_IN_SECONDS: "18000"
  # Account: https://docs.blockscout.com/for-developers/configuration-options/my-account-settings
  ACCOUNT_ENABLED: "false"
  # Smart contract verifier
  MICROSERVICE_SC_VERIFIER_ENABLED: '"{{ blockscout_smart_contract_verifier_enabled }}"'
  MICROSERVICE_SC_VERIFIER_URL: "http://{{ blockscout_smart_contract_verifier_container_name }}:8050/"
  MICROSERVICE_SC_VERIFIER_TYPE: sc_verifier
  MICROSERVICE_ETH_BYTECODE_DB_INTERVAL_BETWEEN_LOOKUPS: 10m
  # Visualizer
  MICROSERVICE_VISUALIZE_SOL2UML_ENABLED: '"{{ blockscout_visualizer_enabled }}"'
  MICROSERVICE_VISUALIZE_SOL2UML_URL: "http://{{ blockscout_visualizer_container_name }}:8050/"
  # Signature provider
  MICROSERVICE_SIG_PROVIDER_ENABLED: '"{{ blockscout_sig_provider_enabled }}"'
  MICROSERVICE_SIG_PROVIDER_URL: "http://{{ blockscout_sig_provider_container_name }}:8050/"
  DECODE_NOT_A_CONTRACT_CALLS: "true"
  VIRTUAL_HOST: "explorer.{{ network_subdomain }}"
  VIRTUAL_PORT: "4000"
  LETSENCRYPT_HOST: "explorer.{{ network_subdomain }}"
