# role: ethpandaops.general.goomy
goomy_container_name: "goomy-txspam1"
goomy_container_image: "ethpandaops/goomy-blob:blobless"
goomy_container_pull: true
goomy_container_networks: "{{ docker_networks_shared }}"
goomy_rpc_urls:
  - "{% for host in groups['execution_node'] %}https://{{ secret_nginx_shared_basic_auth.name }}:{{ secret_nginx_shared_basic_auth.password }}@rpc.{{ host }}.srv.{{ network_subdomain }},{% endfor %}"
goomy_scenario: "eoatx"
goomy_extra_args: ["--max-wallets", "1000", "--throughput", "10", "--max-pending", "20", "--amount", "500", "--random-amount"]
goomy_private_key: "{{ goomy_private_key1 }}"
